### ISSUE TITLE
using Antonym gives an error "Connection Lost False"

### ISSUE THREAD

**Issue by amalhtait** [tasdikrahman/vocabulary#57]
Hello,

When I try to use:
from vocabulary.vocabulary import Vocabulary as vb
print vb.antonym("insane")

I get the error:
Connection Lost 
False

Thanks in advance for your help,
Amal

**Comment by tenorz007** [comment]
Hello @amalhtait 

You get that error if the library is unable to make requests to the API and this happens if a connection can't be made. Be sure you have an active internet connection

**Comment by amalhtait** [comment]
Hello @tenorz007 ,

I was on a VPN connection, once I disconnected from VPN, It worked fine :)
Thank you very much :)
